v2en:
  target: en-vi
  accept_percentage: 0.64
  num_sent: 10
  thread:
    allow: true
    limit: 75
  trans_timeout: 60
  safe_execute: true
  allow:
    GUI: false
    FalseTranslation: true
    time: 300
    resource: 10
    sentences: 0
    tqdm: false
  worksheet: sentences
  sheet: MyDatabase
  amount_exe: 0
  raise_on_error_word: false
training:
  learning_rate: 0.001
  initial_sparsity: 0.0
  final_sparsity: 0.9
  allow_pruning: false
  begin_step: 1
  end_step: 1000
  val_cache_path: ./cache/var.pkl
  model_shape_path: ./cache/shape.pkl
  checkpoint_path: ./models/best.ckpt
