v2en:
  target: en-vi
  accept_percentage: 0.64
  num_sent: 10
  thread:
    allow: true
    limit: 75
  trans_timeout: 60
  safe_execute: true
  allow:
    GUI: false
    FalseTranslation: true
    time: 120
    resource: 10
    tqdm: false
  worksheet: sentences
  sheet: MyDatabase
  amount_exe: 0
training:
  eagerly: false
  use_cpu: false
  num_epochs: 25
  num_train: 100
  sent_len: 500
  validation_split: 0.15
  begin_step: 25
  initial_sparsity: 0.01
  final_sparsity: 0.95
  learning_rate: 0.003
  batch_size: 300
  data_size: 75000
  checkpoint_path: ./models/best
  extension: hdf5
