sqlite:
    path: ./database.db
    table_name: Translation
v2en:
    target: en-vi
    accept_percentage: 0.65
    time_allow: 30
    resource_allow: 1
    num_sent: 10
    thread:
        allow: false
        limit: 0
    trans_timeout: 8