name: run addsent.py

on:
  workflow_dispatch:

jobs:
  execute_python_file:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6' # install the python version needed
          cache: 'pip'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python addsent.py --amount-exe 1 --ci_cd

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
            commit-message: Update database
            title: Update database
            body: Please check the log file before pull
            base: main
            branch: addsent-bot-run
            delete-branch: true
