name: run addsent.py

on:
  workflow_dispatch:

jobs:
  execute_python_file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6" # install the python version needed

      - name: setup client secret
        run: sed -e "s/project_id_value/${{ secrets.PROJECT_ID_VALUE }}/g"
          -e "s/private_key_id_value/${{ secrets.PRIVATE_KEY_ID_VALUE }}/g"
          -e "s/private_key_value/${{ secrets.PRIVATE_KEY_VALUE }}/g"
          -e "s/client_email_value/${{ secrets.CLIENT_EMAIL_VALUE }}/g"
          -e "s/client_id_value/${{ secrets.CLIENT_ID_VALUE }}/g"
          -e "s/client_x509_cert_url_value/${{ secrets.CERT_URL_VALUE }}/g" client_secret_temp.json > client_secret.json

      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - run: pip install -r requirements.txt
        if: steps.cache-pip.outputs.cache-hit != 'true'

      - name: execute py script # run main.py
        run: python addsent.py --amount-exe 1 --ci_cd --disable-thread
