name: run addsent.py

on:
  workflow_dispatch:

jobs:
  execute_python_file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6" # install the python version needed

      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - run: pip install -r requirements.txt
        if: steps.cache-pip.outputs.cache-hit != 'true'

      - name: execute py script # run main.py
        run: python addsent.py --amount-exe 1 --ci_cd --disable-thread

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
