name: Confirm Database Update

on:
  pull_request:
    types:
      - labeled
      - opened
  pull_request_target:
    types: [opened]
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    name: Merge update action
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: Merge update
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "update-database"
          MERGE_DELETE_BRANCH: true
      - name: Feedback
        if: steps.automerge.outputs.automerge == success()
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
